; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = production

[env]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	SPI
	bblanchon/ArduinoJson@^6.21.5
	https://github.com/Steward-Observatory-ETS/NativeEthernet.git
	https://github.com/Steward-Observatory-ETS/NTPClient_Generic.git
	https://github.com/Steward-Observatory-ETS/pubsubclient.git
	https://github.com/Steward-Observatory-ETS/so_sparkplugb.git

[env:production]
build_flags = 
	${env.build_flags}
	-I .pio/libdeps/production/so_sparkplugb/tahu

[env:production_debug]
build_type = debug
build_flags = 
	${env.build_flags}
	-D DEBUG
	-I .pio/libdeps/production_debug/so_sparkplugb/tahu

[env:production_simulated]
build_flags = 
	${env.build_flags}
	-D SIMULATED_POWER_PANEL
	-D DEBUG
	-I .pio/libdeps/production_simulated/so_sparkplugb/tahu

[env:production_simulated_serial]
build_flags = 
	${env.build_flags}
	-D SIMULATED_POWER_PANEL
    -D SIMULATED_SERIAL_PORTS
	-D DEBUG
	-I .pio/libdeps/production_simulated_serial/so_sparkplugb/tahu

[env:development]
build_flags = 
	${env.build_flags}
	-D DEVELOPMENT_SYSTEM
	-D SIMULATED_POWER_PANEL
	-D DEBUG
	-I .pio/libdeps/development/so_sparkplugb/tahu

[env:development_simulated_serial]
build_flags = 
	${env.build_flags}
	-D DEVELOPMENT_SYSTEM
	-D SIMULATED_POWER_PANEL
    -D SIMULATED_SERIAL_PORTS
	-D DEBUG
	-I .pio/libdeps/development_simulated_serial/so_sparkplugb/tahu
